CI: stable libomp install
thaler-lab/Wasserstein pull request #24
Opened 2024-06-18 08:41 UTC by j-s-ashley

For MacOS builds (currently just MacOS-13), this will:
1. [Use the GH checkout action to access the entire LLVM project](https://github.com/j-s-ashley/Wasserstein/blob/fix/libomp-install/.github/workflows/build-wheels.yml#L29)
2. [Build and install OpenMP with appropriate compiler flags](https://github.com/j-s-ashley/Wasserstein/blob/fix/libomp-install/.github/workflows/build-wheels.yml#L36)

2024-06-18 08:46 UTC, j-s-ashley commented
This needs:
- [ ] Commit cleanup from a partially-bungled rebase (some commits don't do what they say they do :clown_face:)
- [ ] Conflict resolution

2024-06-18 20:56 UTC, matthewfeickert requested changes
The pattern

```yaml
      - name: Checkout LLVM on macOS
        uses: actions/checkout@v4
        with:
          repository: llvm/llvm-project
          ref: release/18.x
          path: llvm-project

      - name: Build OpenMP on macOS
        run: |
          cd llvm-project
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=$(brew --prefix) \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DLIBOMP_INSTALL_ALIASES=OFF \
            -S openmp \
            -B build
          cmake \
            --build build \
            --parallel
          cmake --install build
          cd "$GITHUB_WORKSPACE"
```

does the same things that you do (which is already correct) but it uses some CMake niceties to do it with less setup boilerplate and faster.

```
camke ... -S <source code directory> -B <build directory>
```

just sets up all the directories for you without you needing to be physically located in the source dir

```
cmake --build <build directory> --parallel
```

uses a defined build engine and runs in parallel, which means it could be substantially faster than calling `make` explicitly.

```
cmake --install <build directory>
```

is faster as it doesn't trigger the build engine, but just directly does the copy and install step

2024-06-18 20:56 UTC, matthewfeickert commented on .github/workflows/build-wheels.yml
> +      - name: Checkout Wasserstein
```suggestion
      - name: Checkout LLVM on macOS
        uses: actions/checkout@v4
        with:
          repository: llvm/llvm-project
          ref: release/18.x
          path: llvm-project

      - name: Build OpenMP on macOS
        run: |
          cd llvm-project
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=$(brew --prefix) \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DLIBOMP_INSTALL_ALIASES=OFF \
            -S openmp \
            -B build
          cmake \
            --build build \
            --parallel
          cmake --install build
          cd "$GITHUB_WORKSPACE"

      - name: Checkout Wasserstein
```

2024-06-18 20:56 UTC, matthewfeickert commented on .github/workflows/build-wheels.yml
> +        uses: actions/checkout@v3
```suggestion
      - name: Checkout LLVM on macOS
        uses: actions/checkout@v4
        with:
          repository: llvm/llvm-project
          ref: release/18.x
          path: llvm-project

      - name: Build OpenMP on macOS
        run: |
          cd llvm-project
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=$(brew --prefix) \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DLIBOMP_INSTALL_ALIASES=OFF \
            -S openmp \
            -B build
          cmake \
            --build build \
            --parallel
          cmake --install build
          cd "$GITHUB_WORKSPACE"

      - name: Checkout Wasserstein
        uses: actions/checkout@v4
```

2024-06-18 21:04 UTC, matthewfeickert requested changes
Oh, I forgot that also further down in the wheel building is

https://github.com/thaler-lab/Wasserstein/blob/0a0fdeb810fc6f6b55fe773ea75fef7febb02047/.github/workflows/build-wheels.yml#L39-L40

and 

https://github.com/thaler-lab/Wasserstein/blob/0a0fdeb810fc6f6b55fe773ea75fef7febb02047/.github/workflows/build-wheels.yml#L84-L85

which need to get removed as you're doing that in a better way here. :)

This PR could also apply the same patterns to https://github.com/thaler-lab/Wasserstein/blob/0a0fdeb810fc6f6b55fe773ea75fef7febb02047/.github/workflows/ci.yml (if you had that in already and you took it out because of a comment I made, sorry, I was confused) and then remove

https://github.com/thaler-lab/Wasserstein/blob/0a0fdeb810fc6f6b55fe773ea75fef7febb02047/scripts/install-libomp-macos.sh

entirely.

2024-06-19 13:57 UTC, matthewfeickert requested changes

2024-06-19 13:57 UTC, matthewfeickert commented on .github/workflows/build-wheels.yml
> +          cd "$GITHUB_WORKSPACE"
```suggestion
      - name: Build OpenMP on macOS
        env:
          MACOSX_DEPLOYMENT_TARGET: "10.9"
        working-directory: llvm-project
        run: |
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=$(brew --prefix) \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DLIBOMP_INSTALL_ALIASES=OFF \
            -S openmp \
            -B build
          cmake --build build --parallel
          cmake --install build
```

Some additional improvements from @henryiii (https://github.com/thaler-lab/Wasserstein/issues/28#issuecomment-2178283871) RE: `MACOSX_DEPLOYMENT_TARGET`.

2024-06-20 04:17 UTC, matthewfeickert approved these changes
I checked out this branch on my fork and modified it to run all the wheel builds and this passed (:rocket: ), so nice job and I think this LGTM and is ready for a cleaned up commit message summary and merge. :shipit:

2024-06-20 17:37 UTC, merged